[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neutral_density"
version = "2026.2.1"
dependencies = [
    "numpy",
    "scipy",
    "numba"
]
requires-python = ">=3.10"
authors = [
    {name = "Daniel E. Sandborn", email = "sandborn@uw.edu"},
    {name = "Colette L. Kelly", email = "colette.kelly@whoi.edu"},
]
description = "A direct translation of Jackett’s neutral density Fortran suite into Python."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.*"]
keywords = ["oceanography", "python"]
classifiers = [
    "Programming Language :: Python"
]

[tool.setuptools.package-data]
neutral_density = ["*.fdt"]
